### ISSUE TITLE
[Bug] Out of memory error when extending via loops a soundtrack (possible fix by using a 64-bit version?)

### ISSUE THREAD

**Issue by Gui2Barbieri** [libertyernie/LoopingAudioConverter#101]
Hi, so the program works amazingly well overall. The problem I'm having is that it can't extend some tracks to 30 mins, the following error is thrown:

`System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at LoopingAudioConverter.PCM.PCM16Audio.PlayLoopAndFade(Int32 loopCount, Decimal fadeSec)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFileAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFilesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.OptionsForm.<btnOkay_Click>d__48.MoveNext()`

I checked for my RAM, it's 8GB, but I think that's not the problem. The program is 32-bit... could this be the problem? Thanks!

EDIT: More info, it's from Splatoon 3 soundtrack, so we are talking about .bwav files.

**Comment by libertyernie** [comment]
Yeah, it is 32-bit, but I think the only reason is because of the FLAC encoding option that uses Media Foundation via C++. (I had an audio player once that didn't like ffmpeg's FLAC files, but was okay with the Windows ones.) I might take that out of the next release, or maybe move it into a separate .exe file if someone else wants it.

**Comment by Voxybuns** [comment]
Can confirm, trying to convert a BFSTM file into a 30 minute MP3 fails with the following error:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LoopingAudioConverter.PCM.PCM16Audio.PlayAndFade(Decimal duration, Decimal fadeSec)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFileAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFilesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.OptionsForm.<btnOkay_Click>d__48.MoveNext()
```

**Comment by libertyernie** [comment]
I just uploaded a "beta" release (4.3-beta1) that removes the BrawlLib library so it can run in 64-bit mode. Hopefully this'll work for you.

**Comment by Voxybuns** [comment]
> I just uploaded a "beta" release (4.3-beta1) that removes the BrawlLib library so it can run in 64-bit mode. Hopefully this'll work for you.

Unfortunately I'm still getting the same error... Task manager says the app is running in 32-bit mode still, is there any way to force it into x64 mode?

**Comment by libertyernie** [comment]
Looks like it'll only run in 64-bit if it's compiled to run that way. I'll upload a new build.

https://github.com/libertyernie/LoopingAudioConverter/releases/tag/v4.3-beta2

**Comment by Voxybuns** [comment]
Seems to be working for me! I run into a different exception, `Array dimensions exceeded supported range.` but only if I try to convert a track that has a lot of channel pairs - And even then I can just export those as-is, and do a batch conversion with no issues.
