### ISSUE TITLE
Looping Audio Converter 3.1 extremely buggy

### ISSUE THREAD

**Issue by Bonboon229** [libertyernie/LoopingAudioConverter#93]
Changing pitch causes an encoding error
Changing Tempo causes an encoding error
ANYTHING off the default settings causes an encoding error

Fix Your Program Dude

Edit: Contents of written log

LoopingAudioConverter.PCM.AudioImporterException: Could not read ffmpeg output: No data in stream ---> LoopingAudioConverter.WAV.WaveConverterException: No data in stream
   at LoopingAudioConverter.WAV.WaveConverter.FromStream(Stream stream)
   at LoopingAudioConverter.WAV.WaveConverter.FromFile(String filename, Boolean delete)
   at LoopingAudioConverter.FFmpeg.FFmpegEngine.<>c__DisplayClass6_0.<<ApplyEffectsAsync>g__convert|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.FFmpeg.FFmpegEngine.<ApplyEffectsAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at LoopingAudioConverter.FFmpeg.FFmpegEngine.<ApplyEffectsAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFileAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFilesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.OptionsForm.<btnOkay_Click>d__48.MoveNext()

**Comment by Bonboon229** [comment]
Tried the new version. Nothing was fixed. Same Error.
Also of note, VGAudio has not been updated in a very long time. Consider ditching it in favor of VGMStream.

**Comment by libertyernie** [comment]
Is VGMStream capable of creating files like .brstm, or can it only read them?

**Comment by Bonboon229** [comment]
I'll make it a bit clearer. Every single file type errors if pitch/tempo is changed.

**Comment by Bonboon229** [comment]
Edit: Contents of Log File for BRSTM


LoopingAudioConverter.PCM.AudioImporterException: Could not read ffmpeg output: Output file was empty when trying to apply effects, ffmpeg exit code: 1 - see files ffmpeg_stdout.txt, ffmpeg_stderr.txt for details ---> LoopingAudioConverter.PCM.AudioImporterException: Output file was empty when trying to apply effects, ffmpeg exit code: 1 - see files ffmpeg_stdout.txt, ffmpeg_stderr.txt for details
   at LoopingAudioConverter.FFmpeg.FFmpegEngine.<>c__DisplayClass6_0.<<ApplyEffectsAsync>g__convert|1>d.MoveNext() in C:\Users\GojiGoodra\Downloads\LoopingAudioConverter-version-3.0\LoopingAudioConverter.FFmpeg\FFmpegEngine.cs:line 205
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.FFmpeg.FFmpegEngine.<ApplyEffectsAsync>d__6.MoveNext() in C:\Users\GojiGoodra\Downloads\LoopingAudioConverter-version-3.0\LoopingAudioConverter.FFmpeg\FFmpegEngine.cs:line 216
   --- End of inner exception stack trace ---
   at LoopingAudioConverter.FFmpeg.FFmpegEngine.<ApplyEffectsAsync>d__6.MoveNext() in C:\Users\GojiGoodra\Downloads\LoopingAudioConverter-version-3.0\LoopingAudioConverter.FFmpeg\FFmpegEngine.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFileAsync>d__2.MoveNext() in C:\Users\GojiGoodra\Downloads\LoopingAudioConverter-version-3.0\LoopingAudioConverter.Conversion\Converter.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.Conversion.Converter.<ConvertFilesAsync>d__0.MoveNext() in C:\Users\GojiGoodra\Downloads\LoopingAudioConverter-version-3.0\LoopingAudioConverter.Conversion\Converter.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LoopingAudioConverter.OptionsForm.<btnOkay_Click>d__48.MoveNext() in C:\Users\GojiGoodra\Downloads\LoopingAudioConverter-version-3.0\LoopingAudioConverter\OptionsForm.cs:line 444

**Comment by Bonboon229** [comment]
Seems something got screwed up bigtime with ffmpeg

Of note, these problems only started I noticed when you replaced Sox with FFMPEG in 2.5

**Comment by libertyernie** [comment]
Do the files ffmpeg_stdout.txt, ffmpeg_stderr.txt exist? Is there anything in them?

**Comment by Bonboon229** [comment]
I already deleted my copy of  the project folder, but as far as I know, those files were not generated. Just the log.txt

**Comment by Bonboon229** [comment]
Edit: I'm staying FIRMLY with version 2.4 until these problems are PROPERLY fixed

**Comment by Frisk4973** [comment]
im trying to convert the entire stream folder of ctgp7 to bfstm to use with musicrandomizer for splatoon on the FIRST FILE after i press start it crashes

**Comment by UmbraVivens** [comment]
i tried converting a looping wav and doing my usual "import 44100 hz and reencode as 32000 for Brawl BRSTM" doesn't work.
tells me to create a log.txt through cmd and when i do it it says "ffmpeg, qaac, text, etc." can't be found even though they're there

**Comment by libertyernie** [comment]
@UmbraVivens Can you please open a new issue, copy the log.txt into it, and note what version of Looping Audio Converter you're using? I assume 3.1?

**Comment by libertyernie** [comment]
I'm closing this issue because I think the original problem might have been fixed in 3.2 and this issue is attracting comments about unrelated issues that should really be filed separately. If you're still having problems, please open a new issue and include the contents of the log (I've also made a change to the program so it should appear in a window too, whenever an error happens, but the log.txt thing will still work too).
